---
- name: Run application container
  hosts: ec2_instances  
  become: true
  roles:
    - geerlingguy.pip
    - geerlingguy.docker
  
  tasks:

    - name: Update package cache (if needed)
      apt:
        update_cache: yes
      become: yes

    - name: Install python3-pip
      apt:
        name: python3-pip
        state: present
      become: yes

    - name: Pull application image
      docker_image:
        name: hadeer16/test_calc 
        state: present  
        source: pull  

    - name: Start application container
      docker_container:
        name: my_app_container  
        image: hadeer16/test_calc:latest  
        state: started
        ports:
          - "5000:5000"  
