version: '3.8'
services:
  app1:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./visits.json:/app/visits.json

  app2:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - ./visits.json:/app/visits.json